# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

version: 2

includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser.yaml

variables:
  binary_name: markscribe
  description: "Your personal markdown scribe with template-engine and Git(Hub) & RSS powers"
  github_url: "https://github.com/charmbracelet/markscribe"
  maintainer: "Christian Muehlhaeuser <muesli@charm.sh>"
  brew_commit_author_name: "Christian Muehlhaeuser"
  brew_commit_author_email: "muesli@charm.sh"
